apiVersion: v1
kind: ServiceAccount
metadata:
  name: servaccarm
  namespace: finale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cptsparrow
  namespace: finale
rules:          
  - apiGroups:  
      - ''      
      - apps/v1
      - autoscaling
      - batch
      - extentions
      - policy
      - rbac.authorization.k8s.io
    resources:
      - Deployments
    verbs:
      - get
      - list
      - delete
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cptjack
  namespace: finale
roleRef:          
  apiGroups: rbac.authorization.k8s.io
  kind: role
  name: cptsparrow  
subjects:
  - namespace: finale
    kind: Serviceaccount   
    name: servaccarm 
