apiVersion: v1
kind: ServiceAccount
metadata:
  name: serv.acc.arm
  namespace: finale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cpt.sparrow
  namespace: finale
rules:          
  - apiGroups:  
      - ''      
      - apps
      - autoscaling
      - batch
      - extentions
      - policy
      - rbac.authorization.k8s.io
    resources:
      - serviceaccount
    verbs:
      - get
      - list
      - delete
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cpt.jack
  namespace: finale
roleRef:          
  apiGroups: rbac.authorization.k8s.io
  kind: role
  name: cpt.sparrow  
subjects:
  - namespace: finale
    kind: Serviceaccount   
    name: serv.acc.arm 
