apiVersion: apps/v1
kind: Deployment
metadata:
    name: armino.dep
    namespace: finale
spec:
serviceAccountName: servacc
automountServiceAccountToken:
    replicas: 2
  selector:
    matchLabels:
      app: army
  template:
    metadata:
      labels:
        app: army
    spec:
      containers:
      - name: army
        image: picard
        ports:
        - containerport: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: armino.svc
  namespace: finale
spec:
  type: NodePort
  selector:
    app: army
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001

