apiVersion: apps/v1
kind: Deployment
metadata:
    name: arminodep
    namespace: finale
spec:
serviceAccountName: servacc
automountServiceAccountToken:
    replicas: 2
  selector:
    matchLabels:
      app: arminodep
  template:
    metadata:
      labels:
        app: arminodep
    spec:
      containers:
      - name: arminodep
        image: picard
        ports:
        - containerport: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: arminosvc
  namespace: finale
spec:
  type: NodePort
  selector:
    app: arminodep
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001

